### ISSUE TITLE
CV mobile styles

### ISSUE THREAD

**Issue by haensl** [haensl/haensl.github.io.src#37]
Adjust CV mobile styles:

```css
.row > h4 {
  flex-wrap: wrap;
}

.daterange {
  flex: 1 0 7rem;
}
```
